INSERT INTO question (description) VALUES ("У кого есть хвост?");
INSERT INTO question (description) VALUES ("Кто может бегать?");
INSERT INTO question (description) VALUES ("кто мычит?");
INSERT INTO question (description) VALUES ("кто лает?");
INSERT INTO question (description) VALUES ("кто прыгает?");
INSERT INTO question (description) VALUES ("кто хрюкает?");
INSERT INTO question (description) VALUES ("кто может летать?");
INSERT INTO question (description) VALUES ("кто пишет код?");
INSERT INTO answer (description, flag, question_id) VALUES ("белка", b'1', 1);
INSERT INTO answer (description, flag, question_id) VALUES ("шкаф", b'0', 1);
INSERT INTO answer (description, flag, question_id) VALUES ("стул", b'0', 1);
INSERT INTO answer (description, flag, question_id) VALUES ("сейф", b'0', 1);
INSERT INTO answer (description, flag, question_id) VALUES ("кенгуру", b'0', 2);
INSERT INTO answer (description, flag, question_id) VALUES ("кружка", b'1', 2);
INSERT INTO answer (description, flag, question_id) VALUES ("улитка", b'0', 2);
INSERT INTO answer (description, flag, question_id) VALUES ("лось", b'0', 3);
INSERT INTO answer (description, flag, question_id) VALUES ("конь", b'0', 3);
INSERT INTO answer (description, flag, question_id) VALUES ("корова", b'1', 3);
INSERT INTO answer (description, flag, question_id) VALUES ("дверь", b'0', 3);
INSERT INTO answer (description, flag, question_id) VALUES ("собака", b'1', 4);
INSERT INTO answer (description, flag, question_id) VALUES ("кот", b'0', 4);
INSERT INTO answer (description, flag, question_id) VALUES ("мяч", b'0', 4);
INSERT INTO answer (description, flag, question_id) VALUES ("телефон", b'0', 4);
INSERT INTO answer (description, flag, question_id) VALUES ("очки", b'0', 5);
INSERT INTO answer (description, flag, question_id) VALUES ("кенгуру", b'1', 5);
INSERT INTO answer (description, flag, question_id) VALUES ("зеркало", b'0', 5);
INSERT INTO answer (description, flag, question_id) VALUES ("утка", b'1', 7);
INSERT INTO answer (description, flag, question_id) VALUES ("лебедь", b'1', 7);
INSERT INTO answer (description, flag, question_id) VALUES ("пингвин", b'0', 7);
INSERT INTO answer (description, flag, question_id) VALUES ("юрист", b'0', 8);
INSERT INTO answer (description, flag, question_id) VALUES ("программист", b'1', 8);
INSERT INTO answer (description, flag, question_id) VALUES ("футболист", b'0', 8);